# Generated by Django 4.1.5 on 2023-01-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=150)),
                ('laps', models.IntegerField(default=0)),
                ('latitude', models.FloatField()),
                ('longtitude', models.FloatField()),
                ('visitors', models.IntegerField(default=0)),
            ],
        ),
    ]
