# Generated by Django 3.2.6 on 2021-08-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('nationality', models.TextField()),
                ('summarry', models.TextField(default='This is one of the best drivers')),
            ],
        ),
    ]
