# Generated by Django 3.2.6 on 2021-08-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
