# Generated by Django 4.1.5 on 2023-01-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('country', models.CharField(choices=[('United Kingdom', 'United Kingdom'), ('Spain', 'Spain'), ('Netherlands', 'Netherlands'), ('Belgium', 'Belgium '), ('Germany', 'Germany'), ('United States', 'United States'), ('Brasil', 'Brasil '), ('Japan', 'Japan'), ('Australia', 'Australia')], max_length=255)),
                ('length', models.IntegerField(default=0)),
                ('rounds', models.IntegerField(default=0)),
            ],
        ),
    ]
