# Generated by Django 3.2.6 on 2021-09-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0003_auto_20210908_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCompetition', models.TextField(max_length=150)),
                ('lapsLength', models.IntegerField(default=0)),
                ('typeCompetition', models.CharField(choices=[('Formule 1', 'Formule 1'), ('Formule 2', 'Formule 2'), ('Formule 3', 'Formule 3'), ('Porsche', 'Porsche '), ('W series', 'W series')], max_length=255)),
                ('driver', models.ManyToManyField(to='drivers.Drivers')),
            ],
        ),
    ]
