# Generated by Django 4.1.5 on 2023-01-25 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_auto_20210908_1303'),
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=150)),
                ('races', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('Formule 1', 'Formule 1'), ('Formule 2', 'Formule 2'), ('Formule 3', 'Formule 3'), ('Porsche', 'Porsche '), ('W series', 'W series')], max_length=255)),
                ('drivers', models.ForeignKey(default='NoDrivers', on_delete=django.db.models.deletion.CASCADE, to='drivers.drivers')),
            ],
        ),
        migrations.DeleteModel(
            name='Drivers',
        ),
    ]
